name: Build and Release
on: push
jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Add Rust targets
      run: rustup target add x86_64-pc-windows-msvc x86_64-unknown-linux-gnu

    - name: Build windows-x86_64
      run: cargo build --release --target x86_64-pc-windows-msvc

    - name: Build linux-x86_64
      run: cargo build --release --target x86_64-unknown-linux-gnu

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: "Automated release for version ${{ github.ref }}"

    - name: Upload Windows binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/x86_64-pc-windows-msvc/release/github-actions-rust.exe
        asset_name: github-actions-rust-${{ github.ref }}-x86_64-win.exe
        asset_content_type: application/octet-stream

    - name: Upload Linux binary
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: target/x86_64-unknown-linux-gnu/release/github-actions-rust
        asset_name: github-actions-rust-${{ github.ref }}-x86_64-linux
        asset_content_type: application/octet-stream
